name: Deploy to UDC Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Copy build to server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ${{ github.workspace }}/DiscordBot/bin/Release/netcoreapp3.1/
        remote: ${{ secrets.SERVER_BUILD_DIR }}
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}

    - name: Restart Bot
      uses: appleboy/ssh-action@master
      with:
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          ${{ secrets.SERVER_COMMAND }}
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
